routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/tutoriel', function () {
    return view('tuto');
});

Route::resource('articles', 'ArticleController');

Route::get('/contact', function () {
    return view('contact');
});

Route::post('/contact', function () {
    return view('contact');
});

Route::get('/paypal', function () {
    return view('paypal');
});

Route::get('/paid', function () {
    return view('paid');
});

Route::get('/messages', function () {
    return view('messages');
})->middleware('admin');


/* Cart routes */
Route::get('/cart', function () {
    return view('panier');
})->middleware('auth');

Route::get('/cart', 'CartController@index')->name('cart.index');

Route::post('/cart/ajouter','CartController@store')->name('cart.store');

Route::get('/videpanier', function() {
    Cart::destroy();
    return back();
});

Route::delete('/cart/{rowId}', 'CartController@destroy')->name('cart.destroy');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{

    protected $fillable = ['name', 'category_id', 'description', 'price', 'imageUrl', 'quantity'];

    public function order(){
        return $this->belongsTo('App\Order');
    }
    public function category(){
        return $this->hasOne('App\Category');
    }
    public function cart(){
        return $this->belongsTo('App\Cart');
    }
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Article;
use Illuminate\Http\Request;

class ArticleController extends Controller
{

    public function __construct()
    {
        $this->middleware('admin')->only(['create', 'edit', 'destroy']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $articles = Article::all();
        return view('articles.index', ['articles' => $articles]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('articles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'category_id' => 'required|numeric',
            'description' => 'required',
            'price' => 'required|numeric',
            'imageUrl' => 'required',
            'quantity' => 'required|numeric',
        ]);

        $article = new Article();

        $article->name = $request->name;
        $article->category_id = $request->category_id;
        $article->description = $request->description;
        $article->price = $request->price;
        $article->imageUrl = $request->imageUrl;
        $article->quantity = $request->quantity;

        $article->save();

        return redirect()->route('articles.index')->with('success', 'Le produit a bien été ajouté');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $article = Article::find($id);
        return view('articles.show', array('article' => $article));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $article = Article::find($id);
        return view('articles.edit')->with('article', $article);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Article $article)
    {
        $article->update($request->all());
        return redirect()->route('articles.index')->with('success', 'Le produit a bien été edité');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function destroy(Article $article)
    {
        $article->delete();
        return redirect()->route('articles.index');
    }
}

resources/views/articles/create.blade.php
@extends('layouts.master')
@extends('layouts.navbar')

@section('title')

    Covid Shop

@endsection

@section('styles')
@endsection

<div class="container_page">
    <h1 class="text-center" id="main_title">Ajouter un produit</h1>

    <div class="container_content">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">{{ __('Ajouter un produit') }}</div>

                        <div class="card-body">

                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif

                            <form action="{{ route('articles.store') }}" method="POST">
                                @csrf
                                <div class="form-group">
                                    <label for="name">Name: </label>
                                    <input type="text" class="form-control" id="name" name="name">
                                </div>
                                <div class="form-group">
                                    <label for="category_id">Catégorie: </label>
                                    <input type="number" class="form-control" id="category_id" name="category_id">
                                </div>
                                <div class="form-group">
                                    <label for="description">Description: </label>
                                    <input type="text" class="form-control" id="description" name="description">
                                </div>
                                <div class="form-group">
                                    <label for="price">Prix: </label>
                                    <input type="number" class="form-control" id="price" name="price">
                                </div>
                                <div class="form-group">
                                    <label for="imageUrl">Image: </label>
                                    <input type="text" class="form-control" id="imageUrl" name="imageUrl">
                                </div>
                                <div class="form-group">
                                    <label for="quantity">Quantité: </label>
                                    <input type="number" class="form-control" id="quantity" name="quantity">
                                </div>
                                <div class="form-group">
                                    <input type="submit" class="btn btn-success" value="Créer article">
                                    <input type="reset" class="btn btn-danger" value="Effacer">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section('scripts')
@endsection

resources/views/articles/edit.blade.php
@extends('layouts.master')
@extends('layouts.navbar')

@section('title')

    Covid Shop

@endsection

@section('styles')
@endsection

<div class="container_page">
    <h1 class="text-center" id="main_title">Éditer un produit</h1>

    <div class="container_content">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">{{ __('Éditer un produit') }}</div>

                        <div class="card-body">

                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif

                            <form action="{{ route('articles.update', $article->id) }}" method="POST">
                                @csrf
                                {{ method_field('PUT') }}
                                <div class="form-group">
                                    <label for="name">Name: </label>
                                    <input type="text" class="form-control" id="name" name="name"
                                           value="{{$article->name}}">
                                </div>
                                <div class="form-group">
                                    <label for="category_id">Catégorie: </label>
                                    <input type="number" class="form-control" id="category_id" name="category_id"
                                           value="{{$article->category_id}}">
                                </div>
                                <div class="form-group">
                                    <label for="description">Description: </label>
                                    <input type="text" class="form-control" id="description" name="description"
                                           value="{{$article->description}}">
                                </div>
                                <div class="form-group">
                                    <label for="price">Prix: </label>
                                    <input type="number" class="form-control" id="price" name="price"
                                           value="{{$article->price}}">
                                </div>
                                <div class="form-group">
                                    <label for="imageUrl">Image: </label>
                                    <input type="text" class="form-control" id="imageUrl" name="imageUrl"
                                           value="{{$article->imageUrl}}">
                                </div>
                                <div class="form-group">
                                    <label for="quantity">Quantité: </label>
                                    <input type="number" class="form-control" id="quantity" name="quantity"
                                           value="{{$article->quantity}}">
                                </div>
                                <div class="form-group">
                                    <input type="submit" class="btn btn-success" value="Editer l'article">
                                    <input type="reset" class="btn btn-danger" value="Effacer">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section('scripts')
@endsection

resources/views/articles/index.blade.php
@extends('layouts.master')
@extends('layouts.navbar')

@section('title')

    Covid Shop

@endsection

@section('styles')
@endsection





<section class="jumbotron text-center">
    <div class="container">

        <h1 class="text-center" id="main_title">Notre boutique</h1>

        <p class="lead text-muted"> Bienvenue dans la boutique de CovidShop. Vous y trouverez tous nos articles vous
            permettant de vivre plus sereinement ! </p>
        <p>
{{--            <a href="#" class="btn btn-primary my-2">Catégorie 1</a>--}}
{{--            <a href="#" class="btn btn-primary my-2">Catégorie 2</a>--}}
{{--            <a href="#" class="btn btn-primary my-2">Catégorie 3</a>--}}
{{--            <a href="#" class="btn btn-primary my-2">Catégorie 4</a>--}}
        </p>
    </div>
</section>

@if (session('success'))
    <div class="alert alert-success">
        {{ session('success') }}
    </div>
@endif

@foreach($articles->chunk(3) as $articleChunk)
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">
                @foreach($articleChunk as $article)
                    <div class="col-md-4">
                        <div class="card mb-4 shadow-sm">
                            <img class="bd-placeholder-img card-img-top" height="400rem"
                                 src="{{ $article->imageUrl }}" preserveAspectRatio="xMidYMid slice"
                                 focusable="false" role="img" aria-label="Placeholder: Thumbnail">
                            <rect width="100%" height="100%" fill="#55595c"/>
                            <div class="card-body">
                                <h4 class="card-title">{{$article->name}}</h4>
                                <p class="card-text">{{$article->description}}</p>
                                <div class="d-flex justify-content-between align-self-center mt-3">
                                    <div class="d-flex flex-row bd-highlight mb-3">
                                        <a href="{{ url('/articles/' . ($article->id)) }}" type="button"
                                           class="btn btn btn-outline-secondary mr-1"> Description
                                        </a>

                                        <form action="{{ route('cart.store') }}" method="POST">
                                            @csrf

                                            <input type="hidden" name="article_id" value="{{ $article->id }}">
                                            <button type="submit" class="btn btn btn-outline-secondary mr-1"><i
                                                    class="fas fa-cart-plus"></i></button>
                                        </form>

                                        <form method="POST" action="{{route('articles.destroy', $article->id)}}">
                                            @csrf
                                            {{ method_field('DELETE') }}
                                            <button type="submit" class="btn btn-danger"><i class="fas fa-trash mr-1"></i>
                                            </button>
                                        </form>
                                    </div>
                                    <div>
                                        <p class="font-weight-bold">{{$article->price}}€</p>
                                        <p class="text d-flex justify-content-end">Restants : {{$article->quantity}}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </div>
@endforeach
@extends('layouts.footer')

@section('scripts')
@endsection

resources/views/articles/show.blade.php
@extends('layouts.master')
@extends('layouts.navbar')

@section('title')

    Covid Shop

@endsection

@section('styles')
@endsection


<h1 class="text-center titleshow">Notre produit</h1>

<div class=" card mb-3 align-items-center container_cardProduct">
    <div class="card mb-4 shadow-sm" style="width: 25rem;">

        <img class="card-img-top" height="100%"
             src="{{ $article->imageUrl }}" preserveAspectRatio="xMidYMid slice"
             focusable="false" role="img" aria-label="Placeholder: Thumbnail">
        <rect width="100%" height="100%" fill="#55595c"/>
        <div class="card-body">
            <h4 class="card-title">{{$article->name}}</h4>
            <p class="card-text">{{$article->description}}</p>
            <div class="d-flex flex-row justify-content-between align-items-center mt-4">

                <form action="{{ route('cart.store') }}" method="POST">
                    @csrf

                    <input type="hidden" name="article_id" value="{{ $article->id }}">
                    <button type="submit" class="btn btn-dark">Ajouter au panier</button>
                </form>

                <p class="font-weight-bold">{{$article->price}}€</p>
                <p class="text">Restants : {{$article->quantity}}</p>
                <a href="/articles/{{$article->id}}/edit" class="btn btn-info"> Edit</a>
            </div>
        </div>
    </div>
</div>

<!-- START THE FEATURETTES -->

<div class="container_show">
    <h2 class="fournisseurshow">Pourquoi nous choisir ?</h2>

    <div class="row featurette">
        <div class="col-md-7">
            <h2 class="featurette-heading">La Livraison ! <span class="text-muted">Rapide Simple Efficace</span></h2>
            <p class="lead"> Nous suivons vos colis et collaborons avec les transporteurs pour assurer la livraison
                de vos colis dans les meilleurs délais, tout en veillant à la sécurité de chacun.
                Nos produits vous seront livrés de 7 à 10 jours une fois l'expédition de la commande effectuée.</p>
        </div>
        <div class="col-md-5">
            <img class="bd-placeholder-img" width="350" height="250" src="../livraison.jpg">
        </div>
    </div>
    
    
    
    <div class="row featurette">
        <div class="col-md-7 order-md-2">
            <h2 class="featurette-heading">La disponibilité ! <span class="text-muted">Commander quand vous voulez</span>
            </h2>
            <p class="lead"> Nous faisons de notre mieux pour vous satisfaire et donc pour éviter qu'un de nos produits soit
                indisponible. Pour cela nous vérifions chaque jour
                si notre stock de marchandise est assez rempli. Vous pouvez commander sans vous inquiéter sur la
                disponibilité des produits que nous vendons sur notre site.</p>
        </div>
        <div class="col-md-5 order-md-1">
            <img class="bd-placeholder-img" width="600" height="250" src="../stockage2.jpg">
        </div>
    </div>
    
    
    
    <div class="row featurette">
        <div class="col-md-7">
            <h2 class="featurette-heading">La qualité ! <span class="text-muted">Faites nous confiance</span></h2>
            <p class="lead">Face à cette siutation exceptionnelle, notre enseigne s'assure de vous fournir des produits de
                qualité.
                Nos gels et masques respectent les normes de l'AFNOR; ils vous protégerons de la meilleure des façons contre
                le Covid-19.
            </p>
        </div>
    </div>
</div>



<!-- /END THE FEATURETTES -->

@extends('layouts.footer')

@section('scripts')
@endsection